services:
  db:
    image: postgres:18
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql

  s3:
    image: minio/minio:latest
    container_name: minio-s3
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Password123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO Console UI
    volumes:
      - minio_data:/data

volumes:
  data:
  minio_data: